// Package domain defines the core domain model for axi-go,
// a domain-driven execution kernel for semantic actions.
package domain

import (
	"errors"
	"fmt"
	"regexp"
)

// ActionName is the unique identifier of an action. Names must match
// the pattern ^[a-zA-Z][a-zA-Z0-9._-]*$ — use NewActionName to validate.
type ActionName string

// CapabilityName is the unique identifier of a capability. Names follow
// the same validation rules as ActionName; use NewCapabilityName.
type CapabilityName string

// PluginID identifies a plugin contribution. Required non-empty; there
// is no character-set restriction beyond that.
type PluginID string

// ExecutionSessionID identifies one run of an action through the kernel.
// Generated by the configured application.IDGenerator.
type ExecutionSessionID string

var validNamePattern = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9._-]*$`)

// NewActionName validates s and returns it as an ActionName.
// Returns an error if s is empty or contains disallowed characters.
func NewActionName(s string) (ActionName, error) {
	if s == "" {
		return "", errors.New("action name must not be empty")
	}
	if !validNamePattern.MatchString(s) {
		return "", fmt.Errorf("action name %q is invalid: must match %s", s, validNamePattern.String())
	}
	return ActionName(s), nil
}

// NewCapabilityName validates s and returns it as a CapabilityName.
// Returns an error if s is empty or contains disallowed characters.
func NewCapabilityName(s string) (CapabilityName, error) {
	if s == "" {
		return "", errors.New("capability name must not be empty")
	}
	if !validNamePattern.MatchString(s) {
		return "", fmt.Errorf("capability name %q is invalid: must match %s", s, validNamePattern.String())
	}
	return CapabilityName(s), nil
}

// NewPluginID returns s as a PluginID, erroring if s is empty.
func NewPluginID(s string) (PluginID, error) {
	if s == "" {
		return "", errors.New("plugin ID must not be empty")
	}
	return PluginID(s), nil
}

// Contract represents an input or output contract for an action or capability.
type Contract struct {
	Fields []ContractField
}

// ContractField describes a single field in a contract.
type ContractField struct {
	Name        string // Field name (required).
	Type        string // Type hint: "string", "number", "boolean", "object", "array". Empty means any.
	Description string // Human/agent-readable description of what this field is for.
	Required    bool   // Whether this field must be present.
	Example     any    // Example value for documentation and agent guidance.
}

// NewContract returns a Contract containing the given fields.
// Pass nil or an empty slice for a no-field contract; EmptyContract is
// the conventional way to express that.
func NewContract(fields []ContractField) Contract {
	return Contract{Fields: fields}
}

// EmptyContract returns a contract with no fields.
func EmptyContract() Contract {
	return Contract{}
}

// IsEmpty returns true if the contract has no fields.
func (c Contract) IsEmpty() bool {
	return len(c.Fields) == 0
}

// Requirement represents a capability dependency.
type Requirement struct {
	Capability CapabilityName
}

// RequirementSet is a set of requirements with no duplicates.
type RequirementSet []Requirement

// NewRequirementSet builds a RequirementSet from the given requirements,
// erroring if any CapabilityName appears more than once.
func NewRequirementSet(reqs ...Requirement) (RequirementSet, error) {
	seen := make(map[CapabilityName]struct{}, len(reqs))
	for _, r := range reqs {
		if _, exists := seen[r.Capability]; exists {
			return nil, fmt.Errorf("duplicate requirement for capability %q", r.Capability)
		}
		seen[r.Capability] = struct{}{}
	}
	result := make(RequirementSet, len(reqs))
	copy(result, reqs)
	return result, nil
}

// EffectLevel classifies the side effects a capability or action may have.
// The kernel uses this to decide whether execution requires human approval:
// any action whose EffectProfile.Level is EffectWriteExternal pauses at
// AwaitingApproval before its capabilities run.
type EffectLevel string

const (
	EffectNone          EffectLevel = "none"
	EffectReadLocal     EffectLevel = "read-local"
	EffectWriteLocal    EffectLevel = "write-local"
	EffectReadExternal  EffectLevel = "read-external"
	EffectWriteExternal EffectLevel = "write-external"
)

// ValidEffectLevel returns true if the given level is a known effect level.
func ValidEffectLevel(level EffectLevel) bool {
	switch level {
	case EffectNone, EffectReadLocal, EffectWriteLocal, EffectReadExternal, EffectWriteExternal:
		return true
	default:
		return false
	}
}

// IsWriteEffect returns true if the effect level involves writes.
func (p EffectProfile) IsWriteEffect() bool {
	return p.Level == EffectWriteLocal || p.Level == EffectWriteExternal
}

// IsExternalEffect returns true if the effect level involves external systems.
func (p EffectProfile) IsExternalEffect() bool {
	return p.Level == EffectReadExternal || p.Level == EffectWriteExternal
}

// EffectProfile describes the side-effect level of an action, used by
// the kernel to decide whether to gate execution on human approval.
// write-external actions always pause at AwaitingApproval before running.
type EffectProfile struct {
	Level EffectLevel
}

// IdempotencyProfile describes whether an action is idempotent.
type IdempotencyProfile struct {
	IsIdempotent bool
}

// Execution value objects.

// ApprovalDecision records who approved or rejected, and why.
type ApprovalDecision struct {
	Principal string // who approved (user ID, service account, etc.)
	Rationale string // why — free text
}

// Suggestion guides agents toward a logical next action after execution.
// Aligned with axi.md principle #9: contextual next-step suggestions.
type Suggestion struct {
	Action      string // suggested action name
	Description string // why this action makes sense next
}

// ExecutionResult is the payload returned by a successful action execution.
// Data carries the typed result, Summary is a short human-readable line,
// ContentType hints at interpretation, and Suggestions steer agents toward
// the next logical action (axi.md principle #9).
type ExecutionResult struct {
	Data        any
	Summary     string
	ContentType string       // MIME type hint for agents: "text/plain", "application/json", etc.
	Suggestions []Suggestion // contextual next-step hints for agents
}

// FailureReason describes why an action failed. Code is a stable
// machine-readable token (e.g. "budget_exceeded"); Message is human-oriented.
// Action failure is a valid outcome, not a Go error.
type FailureReason struct {
	Code    string
	Message string
}

// EvidenceRecord is one append-only fact about an execution — typically
// a capability output, token-cost report, or trace of a notable branch
// taken during execution. Collected on ExecutionSession and emitted on
// persistence via EvidenceSnapshot.
//
// The Hash and PreviousHash fields form a tamper-evident chain: each
// record's Hash is the SHA-256 of its canonical form concatenated with
// the previous record's hash. They are populated by
// ExecutionSession.AppendEvidence — plugins should leave them empty
// when constructing records; any values set by plugins are ignored
// and overwritten. Verification is available via
// ExecutionSession.VerifyEvidenceChain.
//
// Empty Hash / PreviousHash marks a record as "not part of the chain"
// — typically a pre-1.1 persisted record loaded from an older snapshot,
// or one whose Value could not be canonicalised to JSON. Such records
// are treated as unverifiable (not broken) during chain verification.
type EvidenceRecord struct {
	Kind       string
	Source     string
	Value      any
	Timestamp  int64 // Unix milliseconds. Zero means not set.
	TokensUsed int64 // Tokens consumed by the capability emitting this evidence. Zero means unreported.

	Hash         EvidenceHash // Populated by AppendEvidence; empty means unverifiable.
	PreviousHash EvidenceHash // Populated by AppendEvidence; empty on the chain's head record.
}

// ExecutionStatus represents the state of an execution session.
type ExecutionStatus string

const (
	StatusPending          ExecutionStatus = "pending"
	StatusValidated        ExecutionStatus = "validated"
	StatusResolved         ExecutionStatus = "resolved"
	StatusAwaitingApproval ExecutionStatus = "awaiting_approval"
	StatusRejected         ExecutionStatus = "rejected"
	StatusRunning          ExecutionStatus = "running"
	StatusSucceeded        ExecutionStatus = "succeeded"
	StatusFailed           ExecutionStatus = "failed"
)

// ContributionStatus represents the state of a plugin contribution.
type ContributionStatus string

const (
	ContributionPending ContributionStatus = "pending"
	ContributionActive  ContributionStatus = "active"
)

// ActionExecutorRef is the opaque string binding that links an
// ActionDefinition to its registered ActionExecutor implementation.
// Use PluginBundle to avoid hand-coordinating these strings.
type ActionExecutorRef string

// CapabilityExecutorRef is the opaque string binding that links a
// CapabilityDefinition to its registered CapabilityExecutor implementation.
type CapabilityExecutorRef string
